<a href="https://colab.research.google.com/github/vineet767/matrix/blob/master/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
# Mounting Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Dataset.csv to Dataset.csv


In [ ]:
# Importing the dataset
dataset = pd.read_csv('Dataset.csv')

In [ ]:
print(dataset)

     Gender  Glucose    BP  SkinThickness  ...   BMI  PedigreeFunction  Age  Outcome
0      Male      148  72.0           35.0  ...  33.6             0.627   50        1
1    Female       85  66.0           29.0  ...  26.6             0.351   31        0
2    Female      183  64.0            0.0  ...  23.3             0.672   32        1
3    Female       89  66.0           23.0  ...  28.1             0.167   21        0
4      Male      137   NaN           35.0  ...  43.1             2.288   33        1
..      ...      ...   ...            ...  ...   ...               ...  ...      ...
559    Male       85  74.0            0.0  ...  30.1             0.300   35        0
560    Male      125  76.0            0.0  ...  33.8             0.121   54        1
561    Male      198  66.0           32.0  ...  41.3             0.502   28        1
562    Male       87  68.0           34.0  ...  37.6             0.401   24        0
563    Male       99  60.0           19.0  ...  26.9             

In [35]:
#Print Total number of Rows & columns in dataset
print(dataset.shape)

(564, 9)


In [ ]:
dataset.isnull().sum()

Gender               0
Glucose              0
BP                  16
SkinThickness       11
Insulin             12
BMI                 17
PedigreeFunction    18
Age                  0
Outcome              0
dtype: int64

In [ ]:
# Extracting dependent and independent variables:
# Extracting independent variable:
X = dataset.iloc[:, :-1].values
# Extracting dependent variable:
y = dataset.iloc[:, -1].values

In [ ]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])

In [36]:
# Taking care of missing data
#handling missing data (Replacing missing data with the mean value)  
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values= np.NAN, strategy= 'mean', fill_value=None, verbose=1, copy=True)
#Fitting imputer object to the independent variables x.   
imputer = imputer.fit(X[:, :]) 
#Replacing missing data with the calculated mean value  
X[:, :]= imputer.transform(X[:,:])

In [ ]:
pd.DataFrame(X).isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
dtype: int64

In [32]:
pd.DataFrame(y).isnull().sum()

0    0
dtype: int64

In [31]:
print(X.shape)
print(X)

(564, 8)
[[1.0 148.0 72.0 ... 33.6 0.627 50.0]
 [0.0 85.0 66.0 ... 26.6 0.35100000000000003 31.0]
 [0.0 183.0 64.0 ... 23.3 0.672 32.0]
 ...
 [1.0 198.0 66.0 ... 41.3 0.502 28.0]
 [1.0 87.0 68.0 ... 37.6 0.401 24.0]
 [1.0 99.0 60.0 ... 26.9 0.49700000000000005 32.0]]


In [30]:
print(y.shape)
print(y)

(564,)
[1 0 1 0 1 0 1 0 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 0 0 0 0 0
 1 1 1 0 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 1 0
 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1
 1 0 0 1 1 1 0 0 0 1 0 0 0 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 1 0 1 1 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0
 1 1 1 1 1 0 0 1 1 0 1 0 1 1 1 0 0 0 0 0 0 1 1 0 1 0 0 0 1 1 1 1 0 1 1 1 1
 0 0 0 0 0 1 0 0 1 1 0 0 0 1 1 1 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0
 1 0 1 0 0 1 0 1 0 0 1 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 1 0 0 0 1 1 1 0 0
 1 0 1 0 1 1 0 1 0 0 1 0 1 1 0 0 1 0 1 0 0 1 0 1 0 1 1 1 0 0 1 0 1 0 0 0 1
 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1 0 1 1 0 0 1 0 0 1 0 0 1
 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 1 0 0 1 0 0 1 0 1 1 0 1 0 1 0 1
 0 1 1 0 0 0 0 1 1 0 1 0 1 0 0 0 0 1 1 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1
 1 1 0 0 1 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1
 0 0 0 1 1 0 0 0 0

In [43]:
#Splitting the Dataset into the Training set and Test set

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [44]:
print(X_train)

[[0.0 84.0 0.0 ... 0.0 0.304 21.0]
 [0.0 78.0 50.0 ... 31.0 0.248 26.0]
 [0.0 197.0 70.0 ... 30.5 0.158 53.0]
 ...
 [0.0 196.0 76.0 ... 31.8308957952468 0.875 29.0]
 [1.0 159.0 66.0 ... 30.4 0.38299999999999995 36.0]
 [1.0 85.0 74.0 ... 30.1 0.3 35.0]]


In [46]:
print(X_test)

[[1.0 104.0 76.0 ... 18.4 0.5820000000000001 27.0]
 [0.0 99.0 80.0 ... 19.3 0.284 30.0]
 [1.0 109.0 76.0 ... 27.9 0.64 31.0]
 ...
 [1.0 105.0 68.76824817518248 ... 30.8 0.122 37.0]
 [0.0 187.0 68.0 ... 37.7 0.254 41.0]
 [0.0 154.0 62.0 ... 32.8 0.237 23.0]]


In [47]:
from sklearn.neighbors import KNeighborsClassifier
classifier =  KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [48]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [49]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix: ')
print(cm)

Confusion matrix: 
[[95 21]
 [21 33]]


In [50]:
# calculate Accuracy
from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % (accuracy_score(y_test, y_pred)*100))

Accuracy: 75.29


In [51]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
# calculate precision
# Precision = TruePositives / (TruePositives + FalsePositives)
precision = precision_score(y_test, y_pred, average='micro')
print('Precision: %.3f' % (precision*100))

Precision: 75.294


In [52]:
# calculate recall
# Recall = TruePositives / (TruePositives + FalseNegatives)
recall = recall_score(y_test, y_pred, average='micro')
print('Recall: %.3f' % (recall*100))

Recall: 75.294


In [53]:
# F-Measure = (2 * Precision * Recall) / (Precision + Recall)
# calculate score
score = f1_score(y_test, y_pred, average='micro')
print('F-Measure: %.3f' % (score*100))

F-Measure: 75.294


In [54]:
import pickle 
  
saved_model=pickle.dump(classifier,open('/content/drive/My Drive/mid_term_1.pkl', 'wb')) 